name: Deploy to Yandex Cloud

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync files to Yandex Object Storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.YC_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          AWS_REGION: ru-central1
          SOURCE_DIR: '.'
